version: "3.9"

services:
  scrapper:
    build: scrapper/
    volumes:
      - ./scrapper/:/app
    depends_on:
      - database
  database:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecretpassword
  adminer:
    image: adminer
    restart: always
    ports:
      - 8079:8080
    depends_on:
      - database
  webapp:
    build: web/
    environment:
      FLASK_DEBUG: true
      FLASK_APP: app
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - 8080:5000
    depends_on:
      - database
    volumes:
      - ./web/:/app
